carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
]

store/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.store, name="store"),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),
    
]

uppercut/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', include('admin_honeypot.urls'), name='admin_honeypot'),
    #ทำเก็บคนแอบเข้า admin จบบรรทัดนี้ สั่ง python manage.py migrate จะสร้างตารางเก็บADMIN_HONEYPOT
    path('securelogin/', admin.site.urls), # เข้าadmin
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),

    #ORDERS
    path('orders/', include('orders.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account
# Create your models here.

class Cart(models.Model):
    cart_id     = models.CharField(max_length=250, blank=True)
    date_added  = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user        = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product     = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations  = models.ManyToManyField(Variation, blank=True)
    cart        = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity    = models.IntegerField()
    is_active   = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse
from accounts.models import Account
from django.db.models import Avg, Count


class Product(models.Model):
    product_name    = models.CharField(max_length=200, unique=True)
    slug            = models.SlugField(max_length=200, unique=True)
    description     = models.TextField(max_length=500, blank=True)
    price           = models.IntegerField()
    images          = models.ImageField(upload_to='photo/products')
    stock           = models.IntegerField()
    is_available    = models.BooleanField(default=True)
    category        = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date     = models.DateTimeField(auto_now_add=True)
    modified_date   = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name
    
    class Meta:
        ordering = ['product_name']


    def averageReview(self): # หาค่าเฉลี่ย rating 1-5 จากรายการ review
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)
    
    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True).order_by('id')

variation_category_choice = {
    ('color', 'color'),
    ('size', 'size'),
}

class Variation(models.Model):
    product             = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category  = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value     = models.CharField(max_length=100)
    is_active           = models.BooleanField(default=True)
    created_date        = models.DateTimeField(auto_now_add=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=255)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'ข้อมูล gallery'


class ProductSize(models.Model):
    size_name = models.CharField(max_length=20, blank=False, unique=True)
    is_active  = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
            return self.size_name.upper()

    class Meta:
        verbose_name = 'ไซส์_สินค้า'
        verbose_name_plural = 'รายการไซส์'
        ordering = ['id']

class ProductColor(models.Model):
    color_name = models.CharField(max_length=100, blank=False, unique=True)
    is_active  = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.color_name

    class Meta:
        verbose_name = 'สี_สินค้า'
        verbose_name_plural = 'รายการสี'
        ordering = ['color_name']


class SizeColorStock(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    sizename   = models.ForeignKey(ProductSize, on_delete=models.CASCADE)
    colorname = models.ForeignKey(ProductColor, on_delete=models.CASCADE)
    price = models.IntegerField()
    stock = models.IntegerField()
    is_active  = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'ไซส์/สี/สต๊อก/ราคา'
        verbose_name_plural = 'รายการไซส์/สี/สต๊อก/ราคา'

  

store/forms.py
from django import forms
from .models import ReviewRating

class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

carts/views.py
from re import I
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Product, Variation
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse

# เก็บ cart จาก session ของ browser
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

# เลือกสินค้าเพิ่มเข้ามา , กดปุ่ม +
@login_required(login_url='login')
def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id)  # เก็บ สินค้าไว้ที่ product
    # If the user is authenticated
    if current_user.is_authenticated:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(
                        product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation in ex_var_list:
                # increase the cart item quantity เพิ่มจำนวน
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                user=current_user,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('cart')
    # If the user is not authenticated
    else:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(
                        product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        try:
            # เก็บ cart ใข้ cart_id ปัจจุบัน ใน session
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id=_cart_id(request)
            )
        cart.save()

        is_cart_item_exists = CartItem.objects.filter(
            product=product, cart=cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation in ex_var_list:
                # increase the cart item quantity เพิ่มจำนวน
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(
                    product=product, quantity=1, cart=cart)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)

                item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('cart')

# กดปุ่ม ลบ ลดลงทีละหนึ่ง สุดท้ายลบแถว
def remove_cart(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('cart')


# กดปุ่ม ลบแถวรายการ
def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart')


@login_required(login_url='login')
def cart(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(
                user=request.user, is_active=True).order_by('id')
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True).order_by('id')
            
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (7 * total)/100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }

    return render(request, 'store/cart.html', context)


@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(
                user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (7 * total)/100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass  # just ignore

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
     }
    return render(request, 'store/checkout.html', context)

templates/store/cart.html
{% extends 'base.html'%}

{% load static%}

{% block content%}

<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    {% if not cart_items %}
        <div class="empty" style="padding-top:80px; padding-bottom: 50px;">
            <div class="text-center"style="padding-bottom: 20px;">
                <i class="fa fa-shopping-cart fa-3x"></i>
            </div>
            <h2 class="text-center">รถเข็นว่างเปล่า !</h2>
            <br>
            <div class="text-center">
                <a href="{% url 'store' %}" class="btn btn-secondary">เลือกซื้อสินค้าต่อ..</a>
            </div>
        </div>
    {% else %}
        <div class="row">
        <aside class="col-lg-9">
        <div class="card">
        <table class="table table-borderless table-shopping-cart">
        <thead class="text-muted">
        <tr class="small text-uppercase">
        <th scope="col">รายการสินค้า(ในตะกร้า)</th>
        <th scope="col" width="120" class="text-center">จำนวน</th>
        <th scope="col" width="120">ราคา</th>
        <th scope="col" class="text-right" width="200"> </th>
        </tr>
        </thead>
        <tbody>
        {% for cart_item in cart_items %}  
        <tr>
            <td>
                <figure class="itemside align-items-center">
                    <div class="aside"><a href="{{cart_item.product.get_url}}"><img src="{{cart_item.product.images.url }}" class="img-sm"></a></div>
                    <figcaption class="info">
                        <a href="{{cart_item.product.get_url}}" class="title text-dark">{{ cart_item.product.product_name }}</a>
                        <p class="text-muted small">
                            {% if cart_item.variations.all %}
                                {% for item in cart_item.variations.all %}
                                    {{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }} <br>
                                {% endfor %}
                            {% endif %}
                        </p>
                    </figcaption>
                </figure>
            </td>
            <td> 
                <!-- col.// -->
                <div class="col"> 
                    <div class="input-group input-spinner">
                        <div class="input-group-prepend">
                            <a href="{% url 'remove_cart' cart_item.product.id cart_item.id %}" class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-minus"></i> </a>
                        </div>
                        <input type="text" class="form-control"  value="{{cart_item.quantity }}" disabled>
                        <div class="input-group-append">
                        <form action="{% url 'add_cart' cart_item.product.id %}" method="POST">
                            {% csrf_token %}
                            {% for item in cart_item.variations.all %}
                                <input type="hidden" name="{{ item.variation_category | lower }}" value="{{ item.variation_value | capfirst }}">
                            {% endfor %}
                            <button  class="btn btn-light" type="submit" id="button-plus"> <i class="fa fa-plus"></i> </button>
                        </form>
                        </div>
                    </div> <!-- input-group.// -->
                </div> <!-- col.// -->
            </td>
            <td> 
                <div class="price-wrap"> 
                    <var class="price">{{ cart_item.sub_total }}</var> 
                    <small class="text-muted"> {{cart_item.product.price}} ชิ้น </small> 
                </div> <!-- price-wrap .// -->
            </td>
            <td class="text-right"> 
            <a href="{% url 'remove_cart_item' cart_item.product.id cart_item.id %}" onclick="return confirm('คุณต้องการลบแถวนี้ ใช่หรือไม่?')" class="btn btn-outline-dark"> ลบแถว</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
        </table>
        </div> <!-- card.// -->
        
        </aside> <!-- col.// -->
        <aside class="col-lg-3">
        
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                <dt>รวมราคา:</dt>
                <dd class="text-right">{{total}}</dd>
                </dl>
                <dl class="dlist-align">
                <dt>ภาษี 7%:</dt>
                <dd class="text-right"> {{tax}}</dd>
                </dl>
                <dl class="dlist-align">
                <dt>สุทธิ:</dt>
                <dd class="text-right text-dark b"><strong>{{ grand_total }}</strong></dd>
                </dl>
                <hr>
                <!-- <p class="text-center mb-3">
                    <img src="{% static '/images/misc/payments.png' %}" height="26">
                </p> -->
                <a href="{% url 'checkout' %}" class="btn btn-secondary btn-block"> สั่งซื้อ </a>
                <!-- <a href="./store.html" class="btn btn-light btn-block">Continue Shopping</a> -->
                <a href="{% url 'store' %}" class="btn btn-outline-secondary btn-block"><span class="text">เลือกสินค้าต่อ..</span><i class="fas fa-eye"></i></a>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
        
        </aside> <!-- col.// -->
        
        </div> <!-- row.// -->
    {% endif %}
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<section class="section-content padding-y bg">
  <div class="container">
  
  <!-- ============================ COMPONENT 1 ================================= -->
  <div class="card">
  <div class="row no-gutters">
  <aside class="col-md-6">
  <article class="gallery-wrap"> 
    <div class="img-big-wrap mainImage">
       <center><img src="{{ single_product.images.url }}"></center>
    </div> <!-- img-big-wrap.// -->
    
  </article> <!-- gallery-wrap .end// -->
  <ul class="thumb">
    <li>
      <a href="{{ single_product.images.url }}" target="mainImage"
        ><img src="{{ single_product.images.url }}" alt="Product Image"
      /></a>
      {% for i in product_gallery %}
      <a href="{{i.image.url}}" target="mainImage"><img src="{{i.image.url}}" alt="Product Image"/></a>
      {% endfor %}
    </li>
  </ul>
  </aside>

  <main class="col-md-6 border-left">
    <form action="{% url 'add_cart' single_product.id %}" method="POST">
      {% csrf_token %}
      <article class="content-body">
      
      <h2 class="title">{{ single_product.product_name }}</h2>
      <div class="rating-star"> <!--ใส่ ค่าเฉลี่ยดาว -->
        <span>
          <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1%}-half-o {% endif %}" aria-hidden="true"></i>
          <i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2%}-half-o {% endif %}" aria-hidden="true"></i>
          <i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3%}-half-o {% endif %}" aria-hidden="true"></i>
          <i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4%}-half-o {% endif %}" aria-hidden="true"></i>
          <i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5%}-half-o {% endif %}" aria-hidden="true"></i>
          <span>{{ single_product.countReview }}</span> รีวิว
        </span>
      </div>
  

      <div class="mb-3"> 
        <p>ราคา: <var class="price h4">{{single_product.price}}</var></p>
      </div> 
      
      <p>{{single_product.description}}</p>
      
      <hr>      
        <!-- Color -->
        <div class="row">
          <div class="item-option-select">
            <h6>เลือกสี</h6>
            {% if single_product.variation_set.colors %}
              <radio value="">
                {% for i in single_product.variation_set.colors %}
                  <label class="btn btn-light">
                    <input type="radio" name="color" value="{{ i.variation_value | lower}}" required> {{ i.variation_value | capfirst }}
                  </label>
                {% endfor %}
              </radio>
            {% else %}
              <a style="color: orange;">ไม่พบข้อมูลสี</a>
            {% endif %}
          </div>
        </div>

         <!--Size  -->
        <div class="row">
          <div class="item-option-select">
            <h6>เลือกไซส์</h6>
            {% if single_product.variation_set.sizes %}
              <radio value="">
                {% for i in single_product.variation_set.sizes %}
                  <label class="btn btn-light">
                    <input type="radio" name="size" value="{{ i.variation_value | lower}}" required> {{ i.variation_value | upper }}
                  </label>
                {% endfor %}
              </radio>
            {% else %}
              <a style="color: orange;">ไม่พบข้อมูลไซส์</a>
            {% endif %}
          </div>
        </div>
        <hr>
        {% if single_product.stock <= 0 %}
          <h5 class="text-danger">สินค้าหมด</h5>
        {% else %}
          {% if single_product.variation_set.colors %}
            {% if single_product.variation_set.sizes %}
              <button type="submit" class="btn  btn-secondary"> <span class="text">ใส่ตะกร้า</span> <i class="fas fa-shopping-cart"></i> </button>
            {% endif %}
          {% endif %}
        {% endif %}
      </article> <!-- product-info-aside .// -->
    </form>
  </main> <!-- col.// -->
  </div> <!-- row.// -->
  </div> <!-- card.// -->
  <!-- ============================ COMPONENT 1 END .// ================================= -->
  
  <br>
  
  <div class="row">
  <div class="col-md-9">
  
    <form action="{% url 'submit_review' single_product.id %}" method="POST">
      {% csrf_token %}
      <h5>เขียนรีวิวสินค้า</h5>
      <div>
        <!-- Rating stars -->
        <label>ให้คะแนนเรทติ่งสินค้า</label>
        <br>
        <div class="rate">
          <input type="radio" name="rating" id="rating10" value="5" required/><label for="rating10" title="5"></label>
          <input type="radio" name="rating" id="rating9" value="4.5" required/><label for="rating9" title="4.5" class="half"></label>
          <input type="radio" name="rating" id="rating8" value="4" require /><label for="rating8" title="4"></label>
          <input type="radio" name="rating" id="rating7" value="3.5"  require /><label for="rating7" title="3.5" class="half"></label>
          <input type="radio" name="rating" id="rating6" value="3" require /><label for="rating6" title="3"></label>
          <input type="radio" name="rating" id="rating5" value="2.5" require /><label for="rating5" title="2.5" class="half"></label>
          <input type="radio" name="rating" id="rating4" value="2" require /><label for="rating4" title="2"></label>
          <input type="radio" namd="rating" id="rating3" value="1.5" require /><label for="rating3" title="1.5" class="half"></label>
          <input type="radio" name="rating" id="rating2" value="1" require /><label for="rating2" title="1"></label>
          <input type="radio" name="rating" id="rating1" value="0.5" require /><label for="rating1" title="0.5" class="half"></label>
        </div>
        <br>
        หัวข้อรีวิว:
        <input type="text" class="form-control" name="subject" required>
        <br>
        รีวิว:
        <textarea name="review"  rows="4" class="form-control" required></textarea>
        <br>
        {% if user.is_authenticated %} 
          {% if orderproduct %}
            <input type="submit" value="บันทึก" class="btn btn-secondary"/>
          {% else %}
            <p>คุณต้องซื้อสินค้านี้ก่อนเขียนรีวิว</p>
          {% endif %}
        {% else %}
          <p>
            คุณต้องลงชื่อเข้าใช้และซื้อสินค้าก่อนรีวิว
            <span><a href="{% url 'login' %}"><strong>ลงชื่อเข้าใช้</strong></a></span>
          </p>
        {% endif %}
      </div>
      {% include 'includes/alerts.html'%}
    </form>
    <br>

    <header class="section-heading">
      <h3>รีวิวของลูกค้า </h3>  
      <div class="rating-star">
        <span>
          <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1%}-half-o {% endif %}" aria-hidden="true"></i>
          <i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2%}-half-o {% endif %}" aria-hidden="true"></i>
          <i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3%}-half-o {% endif %}" aria-hidden="true"></i>
          <i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4%}-half-o {% endif %}" aria-hidden="true"></i>
          <i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5%}-half-o {% endif %}" aria-hidden="true"></i>
          <span>{{ single_product.countReview }}</span> รีวิว
        </span>
      </div>
    </header>

    {% for review in reviews %}
      <article class="box mb-3">
        <div class="icontext w-100">
          <!-- <img src="{% static '/images/avatars/avatar1.jpg' %}" class="img-xs icon rounded-circle"> -->
          <div class="text">
            <span class="date text-muted float-md-right">{{ review.updated_at }} </span>  
            <h6 class="mb-1">{{ review.user.full_name }} </h6>
            <div class="rating-star">
              <span>
                <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
              </span>
            </div>
          </div>
        </div> <!-- icontext.// -->
        <div class="mt-3">
          <h6 style="color:rgb(47, 44, 240)">{{ review.subject }}</h6>
          <p>
            {{ review.review }}
          </p>	
        </div>
      </article>
    {% endfor %}
  </div> <!-- col.// -->
  </div> <!-- row.// -->
  
  </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
  
{% endblock %}